create table wmg_rest_sources (
 id          number generated by default on null as identity
             constraint wmg_rest_sources_id_pk primary key
, source_code varchar2(100) not null unique
, url         varchar2(4000) not null
, description varchar2(400)
, active_ind  varchar2(1) default 'Y' not null
, created_by  varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
, created_on  timestamp with local time zone default on null current_timestamp not null
, updated_by  varchar2(60 char)
, updated_on  timestamp with local time zone
);

-- create unique index ux_wmg_rest_sources_code on wmg_rest_sources(source_code);

comment on table wmg_rest_sources is 'registered rest sources for wmg rest util';
comment on column wmg_rest_sources.source_code is 'logical code for the endpoint e.g. wmgt_bot';