PRO .. wmg_player_rank_history 

-- drop table wmg_player_rank_history cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table wmg_player_rank_history (
    id                    number generated by default on null as identity 
                         constraint wmg_player_rank_hist_pk primary key
  , player_id             number not null
  , old_rank_code         varchar2(10)
  , new_rank_code         varchar2(10) not null
  , change_timestamp      timestamp with local time zone not null
  , change_reason         varchar2(500 char)
  , change_type           varchar2(20 char) not null
  , changed_by            varchar2(60 char) not null
  , tournament_session_id number
  , created_on            timestamp with local time zone default on null current_timestamp not null
  , created_by            varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on            timestamp with local time zone
  , updated_by            varchar2(60 char)
  , constraint wmg_player_rank_hist_fk1 foreign key (player_id) references wmg_players(id)
  , constraint wmg_player_rank_hist_fk4 foreign key (tournament_session_id) references wmg_tournament_sessions(id)
)
/

-- Primary lookup: player + timestamp for historical queries
create index wmg_player_rank_hist_i1 on wmg_player_rank_history (player_id, change_timestamp);

-- Index for tournament session lookups
create index wmg_player_rank_hist_i2 on wmg_player_rank_history (tournament_session_id);

comment on table wmg_player_rank_history is 'Historical record of all player rank changes over time';

comment on column wmg_player_rank_history.id is 'Primary Key ID';
comment on column wmg_player_rank_history.player_id is 'Foreign key to wmg_players.id';
comment on column wmg_player_rank_history.old_rank_code is 'Previous rank code (null for initial rank assignment)';
comment on column wmg_player_rank_history.new_rank_code is 'New rank code assigned to player';
comment on column wmg_player_rank_history.change_timestamp is 'When the rank change occurred';
comment on column wmg_player_rank_history.change_reason is 'Optional reason for the rank change';
comment on column wmg_player_rank_history.change_type is 'Type of change: AUTOMATIC, MANUAL, INITIAL, SEASON_END, MIDSEASON';
comment on column wmg_player_rank_history.changed_by is 'User who made the rank change';
comment on column wmg_player_rank_history.tournament_session_id is 'Optional reference to tournament session that triggered the change';
comment on column wmg_player_rank_history.created_by is 'User that created this record';
comment on column wmg_player_rank_history.created_on is 'Date the record was first created';
comment on column wmg_player_rank_history.updated_by is 'User that last modified this record';
comment on column wmg_player_rank_history.updated_on is 'Date the record was last modified';

--------------------------------------------------------
--                        123456789012345678901234567890
create or replace trigger wmg_player_rank_hist_u_trg
before update
on wmg_player_rank_history
referencing old as old new as new
for each row
begin
  :new.updated_on := current_timestamp;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
