create table wmg_rest_request (
  id              number generated by default on null as identity
                 constraint wmg_rest_requestid_pk primary key
, source_code     varchar2(100) not null
, request_time    timestamp with local time zone default on null current_timestamp not null
, http_method     varchar2(10) default 'GET' not null
, endpoint_url    varchar2(4000)
, request_payload clob
, response_payload clob
, status_code     number
, is_error_flag   varchar2(1)
, error_message   varchar2(4000)
, duration_ms     number
, created_by      varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
, created_on      timestamp with local time zone default on null current_timestamp not null
);

alter table wmg_rest_request
 add constraint fk_wmg_rest_request_source
    foreign key (source_code)
    references wmg_rest_sources(source_code);

comment on table wmg_rest_request is 'logs of outbound rest calls, payloads, status and errors';